In [1]:
import torch

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [2]:
x = torch.zeros([2,5])

In [3]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [4]:
x.shape

torch.Size([2, 5])

In [5]:
y = torch.rand([2,5])
y

tensor([[0.3943, 0.9973, 0.1007, 0.5285, 0.5210],
        [0.1926, 0.5798, 0.3224, 0.2740, 0.2812]])

In [6]:
y.view([1,10])

tensor([[0.3943, 0.9973, 0.1007, 0.5285, 0.5210, 0.1926, 0.5798, 0.3224, 0.2740,
         0.2812]])